baseURL: https://bory-kb.github.io/
languageCode: ja-jp
title: Shoma's Shallow Insights
theme: mini

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: UA-123-45

markup:
  highlight:
    guessSyntax: true
    style: emacs
  goldmark:
      renderer:
        unsafe: true


social:
  github: https://github.com/bory-kb
  twitter: https://twitter.com/bory_kb
  linkedin: https://www.linkedin.com/in/shoma-kubo-a05631204/

params:
  author: Shoma Kubo
  bio: InnerSource & Scrum Product Owner
  enableComments: true
  enableGoogleAnalytics: true

